# Discover-K2SmartObjects.ps1
# Queries K2 for existing SmartObjects auto-generated by the SP2013 Broker.
# Instead of deploying NEW SmartObjects, we discover the ones K2 already created
# when the SharePoint 2013 Broker was registered for each site.
#
# Returns JSON array of discovered SmartObjects with their names, properties, and methods.

param(
    [string]$K2Server = "",
    [int]$K2Port = 5555,
    [string]$K2DllPath = "C:\Program Files\K2\Bin",
    [string]$K2User = "",
    [string]$K2Password = "",
    [string]$K2Domain = "",
    [string]$SiteFilter = ""   # Optional: filter by site URL pattern (e.g. "nintexpoc6")
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($K2DllPath)) { $K2DllPath = "C:\Program Files\K2\Bin" }

# Load K2 SDK
[System.AppDomain]::CurrentDomain.AppendPrivatePath($K2DllPath)
foreach ($dll in @("SourceCode.Framework.dll","SourceCode.HostClientAPI.dll","SourceCode.SmartObjects.Authoring.dll","SourceCode.SmartObjects.Management.dll")) {
    $p = Join-Path $K2DllPath $dll
    if (Test-Path $p) {
        try { Unblock-File -Path $p -ErrorAction Stop } catch { }
        [System.Reflection.Assembly]::LoadFrom($p) | Out-Null
    }
}

if ($K2Server -eq "") {
    Write-Host '{"success":false,"error":"K2Server is required"}'
    exit 1
}

try {
    $mgmt = New-Object SourceCode.SmartObjects.Management.SmartObjectManagementServer
    $mgmt.CreateConnection()

    if ($K2User -and $K2Password) {
        $userPart = if ($K2Domain) { "$K2Domain\$K2User" } else { $K2User }
        $connStr = "Integrated=False;IsPrimaryLogin=True;Authenticate=True;EncryptedPassword=False;UserID=$userPart;Password=$K2Password;Host=$K2Server;Port=$K2Port"
    } else {
        $connStr = "Integrated=True;IsPrimaryLogin=True;Authenticate=True;Host=$K2Server;Port=$K2Port"
    }
    $mgmt.Connection.Open($connStr)

    # Get all SmartObjects
    $allSOs = $mgmt.GetSmartObjects()
    $totalSOCount = $allSOs.SmartObjects.Count

    # Filter for SP2013 broker SmartObjects
    # Auto-generated SP broker SOs follow naming: {host}___sites___{sitename}_Lists_{listname}
    # They contain "Lists_" in their name and belong to SP service instances
    $discovered = @()
    $siteFilterNorm = ""
    if ($SiteFilter) {
        # Normalize site filter: http://nintex-sp-poc/sites/nintexpoc6 → nintex_sp_poc___sites___nintexpoc6
        $siteFilterNorm = $SiteFilter -replace '^https?://', ''
        $siteFilterNorm = $siteFilterNorm -replace '[\-\.]', '_'
        $siteFilterNorm = $siteFilterNorm -replace '/', '___'
        $siteFilterNorm = $siteFilterNorm.TrimEnd('_')
    }

    foreach ($so in $allSOs.SmartObjects) {
        $soName = $so.Name

        # Quick filter: only process SOs that look like SP broker auto-generated objects
        $isSpBrokerSO = $false

        # Pattern 1: contains _Lists_ (most common for auto-generated list SOs)
        if ($soName -match '_Lists_') { $isSpBrokerSO = $true }

        # Pattern 2: matches site filter (contains match — "nintexpoc6" matches "*nintexpoc6*")
        if ($siteFilterNorm -and $soName -like "*$siteFilterNorm*") { $isSpBrokerSO = $true }

        if (-not $isSpBrokerSO) { continue }

        # Apply site filter if provided — use contains match, not starts-with
        if ($siteFilterNorm -and $soName -notlike "*$siteFilterNorm*") { continue }

        # Get the SmartObject definition to extract properties and methods
        try {
            $defXml = $mgmt.GetSmartObjectDefinition($false, $soName)

            # Parse out key details
            $soGuid = ""
            $displayName = $soName
            $serviceInstance = ""
            $serviceInstanceGuid = ""
            $serviceObject = ""

            if ($defXml -match 'smartobjectroot[^>]*guid="([a-f0-9\-]+)"') { $soGuid = $Matches[1] }
            if ($defXml -match '<displayname>([^<]+)</displayname>') { $displayName = $Matches[1] }
            if ($defXml -match 'serviceinstance\s+name="([^"]*)"[^>]*guid="([a-f0-9\-]+)"') {
                $serviceInstance = $Matches[1]
                $serviceInstanceGuid = $Matches[2]
            }
            if ($defXml -match '<key name="serviceobject">([^<]+)</key>') { $serviceObject = $Matches[1] }

            # Extract properties
            $properties = @()
            $propMatches = [regex]::Matches($defXml, '<property name="([^"]*)"[^>]*type="([^"]*)"')
            foreach ($m in $propMatches) {
                $propName = $m.Groups[1].Value
                $propType = $m.Groups[2].Value
                # Skip duplicates
                if ($properties | Where-Object { $_.name -eq $propName }) { continue }
                $properties += @{ name = $propName; type = $propType }
            }

            # Extract methods
            $methods = @()
            $methodMatches = [regex]::Matches($defXml, '<method name="([^"]*)"[^>]*type="([^"]*)"')
            foreach ($m in $methodMatches) {
                $methodName = $m.Groups[1].Value
                $methodType = $m.Groups[2].Value
                if ($methods | Where-Object { $_.name -eq $methodName }) { continue }
                $methods += @{ name = $methodName; type = $methodType }
            }

            # Extract list title from the SO name
            $listTitle = ""
            if ($soName -match '_Lists_(.+)$') {
                $listTitle = $Matches[1] -replace '_', ' '
            }

            $discovered += @{
                name = $soName
                guid = $soGuid
                displayName = $displayName
                serviceInstance = $serviceInstance
                serviceInstanceGuid = $serviceInstanceGuid
                serviceObject = $serviceObject
                listTitle = $listTitle
                propertyCount = $properties.Count
                properties = $properties
                methodCount = $methods.Count
                methods = $methods
                status = "existing"
            }
        } catch {
            # Skip SOs we can't read
        }
    }

    $mgmt.Connection.Close()

    $result = @{
        success = $true
        totalSmartObjects = $totalSOCount
        discoveredCount = $discovered.Count
        siteFilter = $SiteFilter
        siteFilterNormalized = $siteFilterNorm
        smartObjects = $discovered
    }
    Write-Host ($result | ConvertTo-Json -Depth 5 -Compress)

} catch {
    $errorMsg = $_.Exception.Message
    if ($_.Exception.InnerException) {
        $errorMsg += " | Inner: " + $_.Exception.InnerException.Message
    }
    Write-Host ('{"success":false,"error":"' + ($errorMsg -replace '"','\"') + '"}')
    exit 1
}
